/**
 * RiskService — the lifecycle, the score rules, and the acceptance threshold.
 *
 * WHY UNIT TESTS WHEN THERE IS AN E2E SUITE. `isms-risk.e2e.spec.ts` drives the real API, the real
 * generated score columns and a real approval through the engine. What it cannot reach cheaply is
 * the BRANCH POINT: that a residual of exactly the threshold takes the approval path while one below
 * it does not, that the direct and approved paths write the same acceptance columns, and that the
 * outstanding-treatment count is taken inside the transition's transaction.
 *
 * The repository, the engine and the transaction are stubs, so what is under test is this service's
 * decisions — not Drizzle, and not the engine's chain.
 */
import { describe, expect, it, vi } from 'vitest';
import { ConflictException, PreconditionFailedException, type DrizzleDB } from '@platform';
import { ACCEPTANCE_APPROVAL_THRESHOLD, RiskService, today } from './risk.service';
import type { Risk, RiskTreatment } from '../domain/risk.types';

const ACTOR = { sub: 'actor-1', email: 'actor@opshub.local' };

function risk(over: Partial<Risk> = {}): Risk {
  const inherentLikelihood = over.inherentLikelihood ?? 4;
  const inherentImpact = over.inherentImpact ?? 4;
  const residualLikelihood = over.residualLikelihood ?? null;
  const residualImpact = over.residualImpact ?? null;
  return {
    id: 'risk-1',
    reference: 'RSK-2026-001',
    title: 'Unpatched edge device',
    description: 'Missing security updates on a perimeter device.',
    category: 'vulnerability',
    assetId: null,
    ownerId: 'owner-1',
    inherentLikelihood,
    inherentImpact,
    // Generated by Postgres in reality; mirrored here so the stub cannot disagree with itself.
    inherentScore: inherentLikelihood * inherentImpact,
    treatmentDecision: null,
    residualLikelihood,
    residualImpact,
    residualScore:
      residualLikelihood === null || residualImpact === null
        ? null
        : residualLikelihood * residualImpact,
    status: 'identified',
    reviewDueOn: null,
    acceptedBy: null,
    acceptedAt: null,
    acceptanceJustification: null,
    acceptedViaRequestId: null,
    closedAt: null,
    closureNote: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    ...over,
  };
}

function treatment(over: Partial<RiskTreatment> = {}): RiskTreatment {
  return {
    id: 'tr-1',
    riskId: 'risk-1',
    description: 'Patch the device',
    ownerId: 'owner-1',
    dueOn: null,
    status: 'planned',
    completedOn: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    ...over,
  };
}

function makeService(repoOver: Record<string, unknown> = {}) {
  const repo = {
    create: vi.fn().mockResolvedValue(risk()),
    findById: vi.fn().mockResolvedValue(risk()),
    findByReference: vi.fn().mockResolvedValue(null),
    list: vi.fn().mockResolvedValue({ rows: [], total: 0 }),
    update: vi
      .fn()
      .mockImplementation((id: string, input: Record<string, unknown>) =>
        Promise.resolve(risk({ id, ...(input as Partial<Risk>) })),
      ),
    transition: vi
      .fn()
      .mockImplementation((id: string, _f: string, to: Risk['status'], extra: Partial<Risk>) =>
        Promise.resolve(risk({ id, status: to, ...extra })),
      ),
    addTreatment: vi.fn().mockResolvedValue(treatment()),
    findTreatmentById: vi.fn().mockResolvedValue(treatment()),
    listTreatments: vi.fn().mockResolvedValue([]),
    updateTreatment: vi
      .fn()
      .mockImplementation((id: string, input: Partial<RiskTreatment>) =>
        Promise.resolve(treatment({ id, ...input })),
      ),
    countOutstandingTreatments: vi.fn().mockResolvedValue(0),
    ...repoOver,
  };
  const TX = { tx: true };
  const transaction = vi.fn((fn: (tx: unknown) => Promise<unknown>) => fn(TX));
  const db = { transaction } as unknown as DrizzleDB;
  const audit = { record: vi.fn().mockResolvedValue(undefined) };
  const engine = { submit: vi.fn().mockResolvedValue({ id: 'req-1' }) };

  const service = new RiskService(repo, db, audit as never, engine as never);
  return { service, repo, db, transaction, audit, engine, TX };
}

describe('identifyRisk', () => {
  it('refuses a duplicate reference before writing anything', async () => {
    const { service, repo } = makeService({ findByReference: vi.fn().mockResolvedValue(risk()) });

    await expect(
      service.identifyRisk(
        {
          reference: 'RSK-2026-001',
          title: 'X',
          description: 'Y',
          category: 'vulnerability',
          ownerId: 'owner-1',
          inherent: { likelihood: 3, impact: 3 },
        },
        ACTOR,
      ),
    ).rejects.toThrow(ConflictException);
    expect(repo.create).not.toHaveBeenCalled();
  });

  it('passes FACTORS, never a score — the score is a generated column', async () => {
    const { service, repo } = makeService();

    await service.identifyRisk(
      {
        reference: 'RSK-2026-002',
        title: 'X',
        description: 'Y',
        category: 'vulnerability',
        ownerId: 'owner-1',
        inherent: { likelihood: 5, impact: 3 },
      },
      ACTOR,
    );

    const written = repo.create.mock.calls[0][0] as Record<string, unknown>;
    expect(written.inherent).toEqual({ likelihood: 5, impact: 3 });
    // Writing a score at all would let the row disagree with its own factors.
    expect(Object.keys(written)).not.toContain('inherentScore');
  });

  it('writes the audit entry inside the transaction', async () => {
    const { service, audit, TX } = makeService();

    await service.identifyRisk(
      {
        reference: 'RSK-2026-003',
        title: 'X',
        description: 'Y',
        category: 'vulnerability',
        ownerId: 'owner-1',
        inherent: { likelihood: 2, impact: 2 },
      },
      ACTOR,
    );

    expect(audit.record).toHaveBeenCalledWith(expect.anything(), TX);
  });
});

describe('updateRisk', () => {
  it('refuses to change a closed risk', async () => {
    const { service, repo } = makeService({
      findById: vi
        .fn()
        .mockResolvedValue(risk({ status: 'closed', closedAt: new Date(), closureNote: 'gone' })),
    });

    await expect(service.updateRisk('risk-1', { title: 'New' }, ACTOR)).rejects.toMatchObject({
      code: 'RISK_NOT_IN_STATE',
    });
    expect(repo.update).not.toHaveBeenCalled();
  });

  it('refuses to drop inherent below an already recorded residual', async () => {
    // `ck_risk_residual_not_worse` compares the FACTORS, so this would otherwise arrive as a 500
    // with no code — the constraint is right, the message is what was missing.
    const { service, repo } = makeService({
      findById: vi
        .fn()
        .mockResolvedValue(risk({ residualLikelihood: 3, residualImpact: 3, status: 'assessed' })),
    });

    await expect(
      service.updateRisk('risk-1', { inherent: { likelihood: 2, impact: 2 } }, ACTOR),
    ).rejects.toMatchObject({ code: 'RISK_INVALID_SCORE' });
    expect(repo.update).not.toHaveBeenCalled();
  });

  it('allows re-scoring an ACCEPTED risk — that is how a register stays honest', async () => {
    const { service, repo } = makeService({
      findById: vi.fn().mockResolvedValue(
        risk({
          status: 'accepted',
          acceptedBy: 'boss-1',
          acceptedAt: new Date(),
          acceptanceJustification: 'carried',
          residualLikelihood: 2,
          residualImpact: 2,
        }),
      ),
    });

    await expect(
      service.updateRisk('risk-1', { inherent: { likelihood: 5, impact: 5 } }, ACTOR),
    ).resolves.toBeTruthy();
    expect(repo.update).toHaveBeenCalled();
  });
});

describe('assessRisk', () => {
  it('refuses a residual worse than the inherent score', async () => {
    const { service, repo } = makeService({
      findById: vi.fn().mockResolvedValue(risk({ inherentLikelihood: 2, inherentImpact: 2 })),
    });

    await expect(
      service.assessRisk(
        'risk-1',
        { decision: 'mitigate', residual: { likelihood: 3, impact: 3 } },
        ACTOR,
      ),
    ).rejects.toMatchObject({ code: 'RISK_INVALID_SCORE' });
    expect(repo.transition).not.toHaveBeenCalled();
  });

  it('allows a residual EQUAL to the inherent score — accepting changes nothing', async () => {
    // `transfer` and `accept` legitimately leave the score where it is; only an INCREASE is wrong.
    const { service } = makeService({
      findById: vi.fn().mockResolvedValue(risk({ inherentLikelihood: 3, inherentImpact: 3 })),
    });

    await expect(
      service.assessRisk(
        'risk-1',
        { decision: 'accept', residual: { likelihood: 3, impact: 3 } },
        ACTOR,
      ),
    ).resolves.toBeTruthy();
  });

  it('records the decision and the residual factors together', async () => {
    const { service, repo } = makeService();

    await service.assessRisk(
      'risk-1',
      { decision: 'mitigate', residual: { likelihood: 2, impact: 1 }, reviewDueOn: '2027-01-01' },
      ACTOR,
    );

    expect(repo.transition).toHaveBeenCalledWith(
      'risk-1',
      'identified',
      'assessed',
      {
        treatmentDecision: 'mitigate',
        residualLikelihood: 2,
        residualImpact: 1,
        reviewDueOn: '2027-01-01',
      },
      expect.anything(),
    );
  });
});

describe('markTreated', () => {
  it('refuses while treatment actions are still open, counted in the transaction', async () => {
    const { service, repo, TX } = makeService({
      findById: vi.fn().mockResolvedValue(risk({ status: 'assessed' })),
      countOutstandingTreatments: vi.fn().mockResolvedValue(2),
    });

    await expect(service.markTreated('risk-1', {}, ACTOR)).rejects.toMatchObject({
      code: 'RISK_TREATMENT_OUTSTANDING',
    });
    // Counted inside the transaction: read on the pool and a concurrently cancelled action could let
    // a risk be declared treated with work still outstanding.
    expect(repo.countOutstandingTreatments).toHaveBeenCalledWith('risk-1', TX);
  });

  it('refuses a risk that is not assessed', async () => {
    const { service, repo } = makeService({
      findById: vi.fn().mockResolvedValue(risk({ status: 'identified' })),
    });

    await expect(service.markTreated('risk-1', {}, ACTOR)).rejects.toMatchObject({
      code: 'RISK_NOT_IN_STATE',
    });
    expect(repo.transition).not.toHaveBeenCalled();
  });

  it('carries a revised residual through when one is supplied', async () => {
    const { service, repo } = makeService({
      findById: vi.fn().mockResolvedValue(risk({ status: 'assessed' })),
    });

    await service.markTreated('risk-1', { residual: { likelihood: 1, impact: 2 } }, ACTOR);

    expect(repo.transition).toHaveBeenCalledWith(
      'risk-1',
      'assessed',
      'treated',
      { residualLikelihood: 1, residualImpact: 2 },
      expect.anything(),
    );
  });
});

describe('acceptRisk', () => {
  /** A risk whose residual sits exactly ON the threshold. */
  const atThreshold = () => risk({ status: 'treated', residualLikelihood: 4, residualImpact: 3 }); // 12

  it('refuses a risk with no residual score', async () => {
    const { service, engine, repo } = makeService({
      findById: vi.fn().mockResolvedValue(risk({ status: 'identified' })),
    });

    await expect(
      service.acceptRisk('risk-1', { justification: 'x'.repeat(20) }, ACTOR),
    ).rejects.toMatchObject({ code: 'RISK_NOT_IN_STATE' });
    expect(engine.submit).not.toHaveBeenCalled();
    expect(repo.transition).not.toHaveBeenCalled();
  });

  it('refuses to accept twice', async () => {
    const { service } = makeService({
      findById: vi.fn().mockResolvedValue(
        risk({
          status: 'accepted',
          residualLikelihood: 1,
          residualImpact: 1,
          acceptedBy: 'b',
          acceptedAt: new Date(),
          acceptanceJustification: 'j',
        }),
      ),
    });

    await expect(
      service.acceptRisk('risk-1', { justification: 'x'.repeat(20) }, ACTOR),
    ).rejects.toMatchObject({ code: 'RISK_NOT_IN_STATE' });
  });

  it('records the acceptance directly BELOW the threshold', async () => {
    const { service, repo, engine } = makeService({
      findById: vi
        .fn()
        .mockResolvedValue(risk({ status: 'treated', residualLikelihood: 3, residualImpact: 3 })), // 9
    });

    const result = await service.acceptRisk(
      'risk-1',
      { justification: 'Low residual and the device retires next quarter.' },
      ACTOR,
    );

    expect(result.requestId).toBeNull();
    expect(result.risk.status).toBe('accepted');
    expect(engine.submit).not.toHaveBeenCalled();
    expect(repo.transition).toHaveBeenCalled();
  });

  it('submits an approval AT the threshold and leaves the risk untouched', async () => {
    // The boundary itself, because `>=` versus `>` is a one-character difference that silently
    // changes who may accept a "high" risk.
    const { service, repo, engine } = makeService({
      findById: vi.fn().mockResolvedValue(atThreshold()),
    });

    const result = await service.acceptRisk(
      'risk-1',
      { justification: 'Compensating controls are in place until the rebuild.' },
      ACTOR,
    );

    expect(result.requestId).toBe('req-1');
    // Nothing is accepted until somebody approves it.
    expect(result.risk.status).toBe('treated');
    expect(repo.transition).not.toHaveBeenCalled();
    expect(engine.submit).toHaveBeenCalledWith(
      'risk_acceptance',
      expect.objectContaining({ riskId: 'risk-1', residualScore: ACCEPTANCE_APPROVAL_THRESHOLD }),
      ACTOR,
    );
  });

  it('freezes the residual score into the request payload', async () => {
    // The approver signs off a specific exposure. If somebody re-scores the risk while the request
    // is open, the number that was approved must remain the number that was shown.
    const { service, engine } = makeService({
      findById: vi
        .fn()
        .mockResolvedValue(risk({ status: 'treated', residualLikelihood: 5, residualImpact: 4 })),
    });

    await service.acceptRisk('risk-1', { justification: 'x'.repeat(20) }, ACTOR);

    const payload = engine.submit.mock.calls[0][1] as { residualScore: number };
    expect(payload.residualScore).toBe(20);
  });
});

describe('applyAcceptance', () => {
  it('writes who, when and why together — the CHECK requires all three', async () => {
    const { service, repo } = makeService();

    await service.applyAcceptance(
      risk({ status: 'treated', residualLikelihood: 4, residualImpact: 3 }),
      {
        approverId: 'boss-1',
        justification: 'Signed off by the CISO.',
        reviewDueOn: '2027-06-01',
        requestId: 'req-9',
      },
      ACTOR,
    );

    const extra = repo.transition.mock.calls[0][3] as Record<string, unknown>;
    expect(extra.acceptedBy).toBe('boss-1');
    expect(extra.acceptanceJustification).toBe('Signed off by the CISO.');
    expect(extra.acceptedViaRequestId).toBe('req-9');
    expect(extra.acceptedAt).toBeInstanceOf(Date);
  });

  it('reuses a supplied transaction rather than opening its own', async () => {
    // Called from the engine's `onApprove`, the acceptance must commit with the approval decision —
    // an approved request pointing at a risk that is still `treated` would be unexplainable.
    const { service, transaction, repo } = makeService();
    const ENGINE_TX = { engineTx: true };

    await service.applyAcceptance(
      risk({ status: 'treated', residualLikelihood: 2, residualImpact: 2 }),
      { approverId: 'boss-1', justification: 'j', reviewDueOn: null, requestId: 'req-9' },
      ACTOR,
      ENGINE_TX as never,
    );

    expect(transaction).not.toHaveBeenCalled();
    expect(repo.transition).toHaveBeenCalledWith(
      'risk-1',
      'treated',
      'accepted',
      expect.anything(),
      ENGINE_TX,
    );
  });

  it('reports a lost race as a conflict', async () => {
    const { service } = makeService({ transition: vi.fn().mockResolvedValue(null) });

    await expect(
      service.applyAcceptance(
        risk({ status: 'treated', residualLikelihood: 2, residualImpact: 2 }),
        { approverId: 'boss-1', justification: 'j', reviewDueOn: null, requestId: null },
        ACTOR,
      ),
    ).rejects.toThrow(ConflictException);
  });
});

describe('closeRisk', () => {
  it('refuses to close twice', async () => {
    const { service, repo } = makeService({
      findById: vi
        .fn()
        .mockResolvedValue(risk({ status: 'closed', closedAt: new Date(), closureNote: 'x' })),
    });

    await expect(service.closeRisk('risk-1', 'again', ACTOR)).rejects.toThrow(
      PreconditionFailedException,
    );
    expect(repo.transition).not.toHaveBeenCalled();
  });

  it('carries the note and the timestamp — the CHECK pairs them', async () => {
    const { service, repo } = makeService();

    await service.closeRisk('risk-1', 'The service was decommissioned.', ACTOR);

    const extra = repo.transition.mock.calls[0][3] as Record<string, unknown>;
    expect(extra.closureNote).toBe('The service was decommissioned.');
    expect(extra.closedAt).toBeInstanceOf(Date);
  });
});

describe('updateTreatment', () => {
  it('fills completedOn with today when the status becomes done', async () => {
    const { service, repo } = makeService();

    await service.updateTreatment('tr-1', { status: 'done' }, ACTOR);

    // `ck_treatment_done_evidence` pairs the two, and making the caller send today's date twice is
    // how one of them ends up missing.
    expect(repo.updateTreatment).toHaveBeenCalledWith(
      'tr-1',
      { status: 'done', completedOn: today() },
      expect.anything(),
    );
  });

  it('respects an explicit completion date', async () => {
    const { service, repo } = makeService();

    await service.updateTreatment('tr-1', { status: 'done', completedOn: '2026-05-05' }, ACTOR);

    expect(repo.updateTreatment).toHaveBeenCalledWith(
      'tr-1',
      { status: 'done', completedOn: '2026-05-05' },
      expect.anything(),
    );
  });

  it('clears completedOn when the status moves away from done', async () => {
    const { service, repo } = makeService({
      findTreatmentById: vi
        .fn()
        .mockResolvedValue(treatment({ status: 'done', completedOn: '2026-05-05' })),
    });

    await service.updateTreatment('tr-1', { status: 'in_progress' }, ACTOR);

    expect(repo.updateTreatment).toHaveBeenCalledWith(
      'tr-1',
      { status: 'in_progress', completedOn: null },
      expect.anything(),
    );
  });

  it('404s for a treatment that does not exist', async () => {
    const { service } = makeService({ findTreatmentById: vi.fn().mockResolvedValue(null) });

    await expect(service.updateTreatment('nope', { status: 'done' }, ACTOR)).rejects.toMatchObject({
      code: 'NOT_FOUND',
    });
  });
});
