/**
 * The loading / failed / empty states of a sub-panel, in one place.
 *
 * WHY THIS IS A COMPONENT. Twenty-five files wrote the same three-branch block by hand before a list:
 *
 *     {q.isLoading && <p className="text-xs text-fg-subtle">Loading…</p>}
 *     {q.isError && <p className="text-xs text-danger">Failed to load …</p>}
 *     {!q.isLoading && !q.isError && rows.length === 0 && <p …>No …</p>}
 *
 * `DataTable` already owns these states for tables. Panels — a list of treatments, a version history, a
 * certificate list — are the same three states in list shape, and writing them by hand meant four of
 * them got it wrong.
 *
 * TWO OF THOSE FOUR ARE WHY THIS EXISTS AT ALL, and they fail in opposite directions:
 *
 *   - `catalogue-tab.tsx` and `cycles-tab.tsx` had no error branch, so a failed load rendered nothing.
 *   - Worse, `cycles-tab.tsx`'s empty test was `!isLoading && total === 0`, which is ALSO true when the
 *     request failed — `data` is undefined, so the count is zero. A failed load therefore claimed "No
 *     reviews in this cycle yet". Not a blank panel: a false statement, in the voice of the product.
 *
 * The order of the branches is the whole point, and it is why this takes the QUERY rather than three
 * booleans: `isError` is checked before emptiness, so a failure can never be reported as an absence.
 *
 * RETURNS NULL WHEN THERE IS DATA, so the caller renders its list unchanged underneath. The component
 * replaces the three-branch preamble, not the list.
 */

/** The parts of a TanStack query this needs. Structural, so a caller may pass its own object. */
export interface PanelQueryState {
  isLoading: boolean;
  isError: boolean;
}

export function PanelState({
  query,
  count,
  empty,
  error = 'Failed to load.',
  emptyTone = 'muted',
}: {
  query: PanelQueryState;
  /** How many rows arrived. `0` with a settled, successful query is the empty state. */
  count: number;
  /** What "nothing here" means on this panel — "No treatment actions", not "No data". */
  empty: string;
  /**
   * What failed, in the panel's own words. Defaults to something true but unhelpful, because a
   * caller that omits it should still not render a silent blank.
   */
  error?: string;
  /**
   * `success` for a panel where EMPTY IS THE GOOD OUTCOME — a coverage report with no gaps, a register
   * with no overdue items.
   *
   * It exists because the alternative was leaving those panels hand-rolled, and one of them was the
   * worst instance of the bug this component fixes: the performance coverage panel had no error branch
   * and an empty test true on failure, so a broken request announced "Everybody in scope has a
   * completed review" in green. A compliance all-clear generated by a failed fetch.
   */
  emptyTone?: 'muted' | 'success';
}) {
  if (query.isLoading) {
    // `role="status"` is polite: it does not interrupt, which is right for a panel filling in below
    // something the reader is already looking at.
    return (
      <p role="status" className="text-xs text-fg-subtle">
        Loading…
      </p>
    );
  }

  if (query.isError) {
    // `role="alert"` here, unlike loading: the reader is waiting for content that is not coming, and
    // finding out by noticing an absence is not finding out.
    return (
      <p role="alert" className="text-xs text-danger">
        {error}
      </p>
    );
  }

  // Only once the query has SETTLED SUCCESSFULLY does a zero count mean "empty". This ordering is the
  // bug that was live in `cycles-tab.tsx`.
  if (count === 0) {
    return (
      <p className={emptyTone === 'success' ? 'text-xs text-success' : 'text-xs text-fg-subtle'}>
        {empty}
      </p>
    );
  }

  return null;
}
